name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    runs-on: ubuntu-latest

  services:
    postgres:
      image: postgres:12
      env:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: clky9912
        POSTGRES_DB: simple_bank
      # Set health checks to wait until postgres has started
      options: >-
        --health-cmd pg_isready
        --health-interval 10s
        --health-timeout 5s
        --health-retries 5
      ports:
        # Maps tcp port 5432 on service container to the host
        - 5432:5432

    steps:
    - uses: actions/checkout@v3

    -name: Run migrations
      run: make migrateup
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.1'

    - name: Test
      run: make test